# 项目启动端口
server:
  address: 0.0.0.0:8000  # 监听所有网络接口
  # debug模式
  model: debug
  # release模式
  #model:release /true/false
  enableSwagger: true

# 数据库配置
db:
  dialects: mysql
  host: 127.0.0.1
  port: 3306
#  db: gin-api
  db: autoops
  username: root
  password: devops@2025
  charset: utf8
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxOpen: 150

# redis配置
redis:
#  address: 127.0.0.1:6379
  address: 127.0.0.1:6379
  password: "123456"

# 图片地址和ip
imageSettings:
  # 本地磁盘地址
  uploadDir: ./upload/

# log日志配置
log:
  path: ./log
  name: sys
  # 输出到控制台
  model: console
  # 输出到文件
  # model: file

# 监控配置
monitor:
  prometheus:
    url: "http://127.0.0.1:9090"
  pushgateway:
    url: "http://127.0.0.1:9091"
  agent:
    heartbeat_server_url: "http://127.0.0.1:8000/api/v1/monitor/agent/heartbeat"
    heartbeat_token: "agent-heartbeat-token-2024"
  webhook:
    token: "webhook-notify-token-2024"
